# Generated by Django 4.0.4 on 2022-05-25 11:50

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("fly_code", models.CharField(max_length=125)),
                ("source", models.CharField(max_length=125)),
                ("target", models.CharField(max_length=125)),
                ("price", models.IntegerField()),
                ("date", models.CharField(max_length=125)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=125)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("en_name", models.CharField(max_length=125)),
                ("en_family", models.CharField(max_length=125)),
                (
                    "gender",
                    models.CharField(
                        choices=[("مرد", "مرد"), ("زن", "زن")], max_length=12
                    ),
                ),
                ("national_code", models.CharField(max_length=10)),
                ("ir_name", models.CharField(max_length=125)),
                ("ir_family", models.CharField(max_length=125)),
                ("day", models.PositiveSmallIntegerField()),
                ("month", models.CharField(max_length=25)),
                ("year", models.PositiveSmallIntegerField()),
                ("price", models.IntegerField()),
                ("age", models.CharField(max_length=125)),
                (
                    "reserve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="passangers.reservation",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
