# Generated by Django 4.0.4 on 2022-05-25 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passangers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'مسافر', 'verbose_name_plural': 'مسافر ها'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده؟'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.CharField(max_length=125, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='day',
            field=models.PositiveSmallIntegerField(verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='en_family',
            field=models.CharField(max_length=125, verbose_name='نام لایتن'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=12, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ir_family',
            field=models.CharField(max_length=125, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ir_name',
            field=models.CharField(max_length=125, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='month',
            field=models.CharField(max_length=25, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='passangers.reservation', verbose_name='رزرو کننده'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=125, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='fly_code',
            field=models.CharField(max_length=125, verbose_name='کد پرواز'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=125, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.CharField(max_length=125, verbose_name='مبذا'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='target',
            field=models.CharField(max_length=125, verbose_name='مقصد'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
