# Generated by Django 4.0.4 on 2022-05-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='عنوان سایت')),
                ('logo', models.ImageField(upload_to='', verbose_name='لوگو')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('instagram', models.URLField(verbose_name='اینستاگرام')),
                ('telegram', models.URLField(verbose_name='تلگرام')),
                ('whatsapp', models.URLField(verbose_name='واتساپ')),
                ('copyrights', models.CharField(max_length=500, verbose_name='کپی رایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
            },
        ),
    ]
