# Generated by Django 4.0.4 on 2022-05-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='فیس بوک'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='واتساپ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='اینستاگرام'),
        ),
    ]
