# Generated by Django 4.0.4 on 2022-05-25 04:10

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models

import accounts.uitils


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "national_card",
                    models.ImageField(upload_to=accounts.uitils.get_file_path),
                ),
                (
                    "identity_card",
                    models.ImageField(upload_to=accounts.uitils.get_file_path),
                ),
                (
                    "passport",
                    models.ImageField(
                        blank=True, upload_to=accounts.uitils.get_file_path
                    ),
                ),
                (
                    "other",
                    models.ImageField(
                        blank=True, upload_to=accounts.uitils.get_file_path
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
