# Generated by Django 4.0.4 on 2022-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_otpcode_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="bind",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="phone_number",
            field=models.CharField(max_length=11, verbose_name="شماره تماس"),
        ),
    ]
