# Generated by Django 4.0.4 on 2022-05-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdocument_bind_alter_otpcode_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
    ]
